// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/home/camilotorres/Documents/University/JovenInvestigador_GFIF/WorkDir/Bu2/MCanalysis/./BuFit_MC.C";

#endif
